plugins {
    id "com.android.application"
}

def keystorePath = System.getenv("KEYSTORE_PATH")

android {
    namespace "com.abumohamed.ecotools"
    compileSdk 34

    defaultConfig {
        applicationId "com.abumohamed.ecotools"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            if (keystorePath) {
                storeFile file(keystorePath)
                storeType "pkcs12"
                storePassword System.getenv("STORE_PASSWORD")
                keyAlias System.getenv("KEY_ALIAS")
                keyPassword System.getenv("KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (keystorePath) {
                signingConfig signingConfigs.release
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
